# Change these first
owner: RainySystems # Your GitHub organization or username, where this repository lives
repo: RainyUptime # The name of this repository

sites:
  - name: RainySystems HomePage
    url: https://RainySystems.ch
  - name: RainySystems API
    url: https://api.rainysystems.ch
  - name: RainyDo
    url: https://RainyDo.ch
  - name: RainyDo API
    url: https://api.rainysystems.ch
  - name: Stormki Homepage
    url: https://Stormki.net

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: uptime.rainysystems.ch
  # baseUrl: /your-repo-name
  logoUrl: https://rainysystems.ch/assets/img/avatars/RainySystems_Mascot.png
  name: RainySystems
  introTitle: Welcome to our **Monitoring** page.
  introMessage: This is the **Monitoring Page** for all RainySystems offered Systems. If you have issues to use our services first look here. If you still encounter problems reaching our services you can contact us at contact@rainysystems.ch
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
